### LOGIN 
POST http://localhost:4000/api/auth/login 
Content-Type: application/json 
{
    "email": "stevans932@gmail.com", 
    "password": "312392"
}

POST http://localhost:4000/api/auth/register
Content-Type: application/json
{
    "firstName": "Stevan 2",
    "lastName": "Stevanovic 2",
    "email": "stevans9322@gmail.com",
    "password": "312392"
}