### GET ALL USERS 
GET http://localhost:4000/api/user/all

### DELETE USER
DELETE http://localhost:4000/api/user/6716a3fe77b1e34fe97f6088

### UPDATE USER 
PUT http://localhost:4000/api/user/6716d4db65c7d9e1904706c3
Content-Type: application/json
{
    "firstName": "Stevan 3",
    "lastName": "Stevanovic 3",
    "email": "stevans93@gmail.com",
    "password": "312392"
}

### GET USER
GET http://localhost:4000/api/user/6716d4db65c7d9e1904706c3