### LOGIN 
POST http://localhost:4000/api/auth/login 
Content-Type: application/json 
{
    "email": "stevans932234@gmail.com", 
    "password": "312392"
}

### REGISTER 
POST http://localhost:4000/api/auth/register
Content-Type: application/json
{
    "firstName": "Stevan 3",
    "lastName": "Stevanovic 3",
    "email": "stevans932234@gmail.com",
    "password": "312392"
}